from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Frame
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from io import BytesIO
from datetime import datetime

def safe_str(v):
    return "" if v is None else str(v)

class FooterCanvas(canvas.Canvas):
    def __init__(self, *args, footer_subtitle="Generated by Unit Plan Reviewer", **kwargs):
        super().__init__(*args, **kwargs)
        self.footer_subtitle = footer_subtitle
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        self._saved_page_states.append(dict(self.__dict__))
        page_count = len(self._saved_page_states)
        for page_number, state in enumerate(self._saved_page_states, start=1):
            self.__dict__.update(state)
            self._draw_footer(page_number, page_count)
            super().showPage()
        super().save()

    def _draw_footer(self, page_number, page_count):
        w, _ = self._pagesize
        self.setFont("Helvetica", 8)
        self.drawCentredString(w / 2, 0.55 * inch, f"Page {page_number}")
        self.setFont("Helvetica-Oblique", 8)
        self.drawCentredString(w / 2, 0.4 * inch, self.footer_subtitle)

def wrap_text(c, text, x, y, max_width, font_name="Helvetica", font_size=9, leading=None):
    """
    Wrap text to fit within max_width and return the new y position.
    """
    if leading is None:
        leading = font_size * 1.2
    
    # Create a paragraph style
    styles = getSampleStyleSheet()
    style = ParagraphStyle(
        'CustomStyle',
        parent=styles['Normal'],
        fontName=font_name,
        fontSize=font_size,
        leading=leading,
        alignment=TA_LEFT,
    )
    
    # Create paragraph
    para = Paragraph(text, style)
    
    # Calculate available height (estimate)
    available_height = y - inch
    
    # Create a frame and draw
    frame = Frame(x, y - available_height, max_width, available_height, 
                  leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0)
    
    # Wrap the paragraph
    w, h = para.wrap(max_width, available_height)
    
    # Draw it
    para.drawOn(c, x, y - h)
    
    # Return new y position
    return y - h - (leading * 0.5)

def _severity_color(severity: str) -> tuple:
    colors = {
        "High": (0.78, 0.1, 0.1),
        "Medium": (0.9, 0.55, 0.1),
        "Low": (0.15, 0.6, 0.3),
    }
    return colors.get(severity, (0, 0, 0))


def _get_effective_severity(issue, annotations) -> str:
    if not annotations:
        return issue.severity
    overrides = annotations.get("severity_overrides", {}) or {}
    issue_id = getattr(issue, "issue_id", None)
    return overrides.get(issue_id, issue.severity)


def build_pdf_report(result, annotations=None):
    buf = BytesIO()
    c = FooterCanvas(buf, pagesize=letter)
    w, h = letter
    # Define margins
    left_margin = inch
    right_margin = w - inch
    max_text_width = right_margin - left_margin
    
    # Define margins
    left_margin = inch
    right_margin = w - inch
    max_text_width = right_margin - left_margin

    # ===== COVER PAGE =====
    y = h - 2 * inch
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    title = f"Accessibility Review Report"
    c.drawCentredString(w / 2, y, title)
    y -= 0.5 * inch
    
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(w / 2, y, safe_str(result.project_name))
    y -= 1 * inch
    
    # Metadata box
    c.setFont("Helvetica", 11)
    c.drawString(left_margin + 0.5*inch, y, f"Ruleset: {safe_str(result.ruleset)}")
    y -= 0.3 * inch
    c.drawString(left_margin + 0.5*inch, y, f"Scale: {safe_str(result.scale_note)}")
    y -= 0.3 * inch
    c.drawString(left_margin + 0.5*inch, y, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    y -= 0.3 * inch
    c.drawString(left_margin + 0.5*inch, y, f"Pages Reviewed: {len(result.pages)}")
    y -= 0.3 * inch
    
    total_issues = sum(len(page.issues) for page in result.pages)
    c.drawString(left_margin + 0.5*inch, y, f"Total Issues Found: {total_issues}")
    y -= 1 * inch
    
    # Overall summary
    if result.overall_summary:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left_margin, y, "Executive Summary")
        y -= 0.3 * inch
        
        c.setFont("Helvetica", 10)
        y = wrap_text(c, safe_str(result.overall_summary), left_margin, y, max_text_width, "Helvetica", 10)
        y -= 0.5 * inch
    
    # Disclaimer
    c.setFont("Helvetica-Oblique", 8)
    disclaimer = (
        "DISCLAIMER: This review is provided as preliminary guidance only and does not replace "
        "professional judgment, field verification, or jurisdictional review. All measurements "
        "and findings should be verified on-site before making final decisions."
    )
    y = wrap_text(c, disclaimer, left_margin, y, max_text_width, "Helvetica-Oblique", 8)
    
    # Start new page for content
    c.showPage()
    y = h - inch

    # ===== DETAILED FINDINGS =====
    issue_num = 1
    for page in result.pages:
        # Check if we need a new page
        if y < 2 * inch:
            c.showPage()
            y = h - inch

        # Page header with background
        c.setFillColorRGB(0.9, 0.9, 0.9)
        c.rect(left_margin - 0.1*inch, y - 0.35*inch, max_text_width + 0.2*inch, 0.4*inch, fill=True, stroke=False)
        c.setFillColorRGB(0, 0, 0)
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left_margin, y - 0.25*inch, f"Page {page.page_index} — {safe_str(page.page_label)}")
        y -= 0.5 * inch
        
        # Sheet info
        c.setFont("Helvetica", 9)
        sheet_no = getattr(page, "sheet_number", None) or getattr(page, "sheet_id", None) or "N/A"
        sheet_title = getattr(page, "sheet_title", None) or "N/A"
        sheet_text = f"Sheet: {safe_str(sheet_no)} — {safe_str(sheet_title)}"
        c.drawString(left_margin, y, sheet_text)
        y -= 0.25 * inch
        
        # Review confirmation
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(left_margin, y, "Review confirmation: Drawing image reviewed by AI model.")
        y -= 0.3 * inch

        # Page summary with wrapping
        if page.summary:
            c.setFont("Helvetica-Oblique", 9)
            y = wrap_text(c, f"Summary: {safe_str(page.summary)}", left_margin, y, max_text_width, "Helvetica-Oblique", 9)
            y -= 0.3 * inch

        if not page.issues:
            c.setFont("Helvetica", 9)
            c.drawString(left_margin, y, "✓ No issues reported for this page.")
            y -= 0.4 * inch
        else:
            for idx, issue in enumerate(page.issues, 1):
                # Check if we need a new page before each issue
                if y < 2.5 * inch:
                    c.showPage()
                    y = h - inch
                
                # Issue number and severity badge
                effective_severity = _get_effective_severity(issue, annotations)
                c.setFont("Helvetica-Bold", 10)
                c.setFillColorRGB(*_severity_color(effective_severity))
                severity_symbol = {"High": "●", "Medium": "◐", "Low": "○"}
                header = (
                    f"{issue_num}. {severity_symbol.get(effective_severity, '○')} "
                    f"[{effective_severity}] {safe_str(issue.location_hint)}"
                )
                c.drawString(left_margin, y, header)
                c.setFillColorRGB(0, 0, 0)
                y -= 0.2 * inch
                
                # Confidence indicator
                c.setFont("Helvetica-Oblique", 8)
                c.drawString(left_margin + 0.2*inch, y, f"Confidence: {safe_str(issue.confidence)}")
                y -= 0.2 * inch
                
                # Finding with wrapping
                c.setFont("Helvetica", 9)
                finding_text = f"<b>Finding:</b> {safe_str(issue.finding)}"
                y = wrap_text(c, finding_text, left_margin + 0.2*inch, y, max_text_width - 0.2*inch, "Helvetica", 9)
                y -= 0.15 * inch
                
                # Measurement if present
                if issue.measurement:
                    c.setFont("Helvetica", 9)
                    meas_text = f"<b>Measured:</b> {safe_str(issue.measurement)}"
                    y = wrap_text(c, meas_text, left_margin + 0.2*inch, y, max_text_width - 0.2*inch, "Helvetica", 9)
                    y -= 0.15 * inch
                
                # Recommendation with wrapping
                rec_text = f"<b>Recommendation:</b> {safe_str(issue.recommendation)}"
                y = wrap_text(c, rec_text, left_margin + 0.2*inch, y, max_text_width - 0.2*inch, "Helvetica", 9)
                y -= 0.15 * inch
                
                # Reference if present
                if issue.reference:
                    c.setFont("Helvetica-Oblique", 8)
                    ref_text = f"<b>Reference:</b> {safe_str(issue.reference)}"
                    y = wrap_text(c, ref_text, left_margin + 0.2*inch, y, max_text_width - 0.2*inch, "Helvetica-Oblique", 8)
                    y -= 0.15 * inch

                y -= 0.3 * inch
                issue_num += 1
        
        y -= 0.2 * inch

    c.save()
    return buf.getvalue()
